# Generated by Django 4.2.3 on 2023-08-14 06:38

import app_catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=app_catalog.models.directory_path)),
                ('parent_category', models.ForeignKey(blank=True, limit_choices_to={'parent_category__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
