# Generated by Django 4.2.3 on 2023-08-26 03:48

import app_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='Default-avatar.jpg', null=True, upload_to=app_user.models.directory_path),
        ),
    ]
