# Generated by Django 4.2.3 on 2023-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(default='No name', max_length=100),
        ),
    ]
