# Generated by Django 4.2.3 on 2023-08-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ManyToManyField(blank=True, to='app_product.product'),
        ),
    ]
