# Generated by Django 4.2.3 on 2023-08-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='src',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.product'),
        ),
    ]
