# Generated by Django 4.2.3 on 2023-08-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited',
            field=models.BooleanField(default=False),
        ),
    ]
