# Generated by Django 4.2.3 on 2023-08-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_product_date_from_product_date_to_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_from',
            new_name='dateFrom',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_to',
            new_name='dateTo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='salePrice',
        ),
    ]
