# Generated by Django 4.2.3 on 2023-08-01 07:28

import app_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_alter_productreview_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=app_product.models.product_images_directory_path),
        ),
    ]
