# Generated by Django 4.2.3 on 2023-09-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_rename_date_from_product_datefrom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dateFrom',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dateTo',
            new_name='date_to',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='salePrice',
            new_name='sale_price',
        ),
    ]
