# Generated by Django 4.2.3 on 2023-09-06 05:18

import app_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_rename_datefrom_product_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='src',
            field=models.ImageField(max_length=500, upload_to=app_product.models.directory_path),
        ),
    ]
